### ISSUE TITLE
Storm 0.9.1-incubating not properly parsed in cmdline.py

### ISSUE THREAD

**Issue by jmccarthy14** [AirSage/Petrel#56]
When choosing which artifact to make, the maven pom looks for `0.9.1-incubating` in the `-Dstorm_version` argument, but cmdline.py parses the environment's current storm version in a \d.\d.\d format

`m = re.search('^\d\.\d\.\d', version)`

meaning `-Dstorm_version` passed to maven will Never fit the correct `0.9.1-incubating` format, just `0.9.1`, and the correct jar file will not be created. (It defaults to 0.9.0-SNAPSHOT.jar)

**Comment by barrywhart** [comment]
I made some fixes today for 0.9.2 and 0.9.3. I also tested 0.9.1, which is working fine for me. Can you confirm it's working for you?
