### ISSUE TITLE
Multiple streams

### ISSUE THREAD

**Issue by killer14** [AirSage/Petrel#64]
Hi,

I have just started learning Storm and I find things too technical on the internet. Can you please give me simple example for multiple streams. Lets take an example where you have text file. Spouts emit line and a bolt splits the emitted line into words and emit the words. Based on what word it is the corresponding bolt should be executed. Eg if the word is major..major bolt should be executed. So can you please give me code example for this. Also id you can help me learn some other new topic in the example.. It would be my pleasure to learn new concept as a newbie.

Can you please send me useful links to learn storm.

**Comment by barrywhart** [comment]
Here's an earlier ticket that uses multiple streams. It includes some example code. https://github.com/AirSage/Petrel/issues/28
