### ISSUE TITLE
emitter.py

### ISSUE THREAD

**Issue by CogumelosMaravilha** [AirSage/Petrel#73]
Hi Barry,

I'm working on a new Storm/Petrel project and I'm getting:
petrel-0.10.0.0.3-py2.7.egg/petrel/emitter.py", line 22, in declareOutputFields
raise NotImplementedError()

Where do I need to look harder in my code?

Thanks.

**Comment by barrywhart** [comment]
Each spout or bolt needs to implement this function itself. The one in emitter.py is just a base class placeholder.

You can see examples of this in the spouts and bolts under https://github.com/AirSage/Petrel/blob/master/samples/wordcount.
