### ISSUE TITLE
Storm 1.0 and Petrel 1.0

### ISSUE THREAD

**Issue by CogumelosMaravilha** [AirSage/Petrel#75]
Hi all,

Petrel last upgrade for Storm 0.10 was really fast and with small changes to the code.
I have a problem with Storm, so I checked the change log and is fixed in the new version.
Can we have Petrel 1.0?

Thanks in advance.

**Comment by barrywhart** [comment]
I'll take a look. It's usually as simple as updating a Maven build file and rebuilding.

**Comment by barrywhart** [comment]
This is going to take some digging. The Thrift definitions for Storm 1.0 will not compile with the same Thrift compiler that worked in the past. (And Storm uses its own fork of Thrift as well, at least in the past.)

I may have something in the next few days.

**Comment by CogumelosMaravilha** [comment]
Hi Barry,

Thanks for trying a quick fix, but now you need to dig. Sorry.

Thanks a lot and good work.

**Comment by CogumelosMaravilha** [comment]
Hi Barry,
In the meantime there's Storm 1.0.1. What do you think step by step, or a jump to the last version?

Thanks.

**Comment by barrywhart** [comment]
Storm 1.0 and subsequent versions have some odd changes to the Thrift definitions which prevent using the Python code generation tools (unless I hack storm.thrift to work around this, which I do not want to do).

I have logged an issue against Storm to ask if they can fix this:
https://issues.apache.org/jira/browse/STORM-1842

**Comment by CogumelosMaravilha** [comment]
I have comment the issue.
Thanks Barry.

**Comment by barrywhart** [comment]
The Thrift forward reference pull request fixes that issue.

I have learned that in Storm 1.0, a number of Java types were moved to new namespaces, causing other problems.

**Comment by barrywhart** [comment]
I have built and uploaded Petrel 1.0.1.0.3 to pypi.python.org. I believe this addresses all the issues introduced in Storm 1.0.x.

**Comment by CogumelosMaravilha** [comment]
Hi Barry,
Can I use the vanilla Apache Storm version 1.0.1?
The Apache team path the 1.0.1 version and prepare a custom version for you to test.

**Comment by barrywhart** [comment]
Yes, that's how I tested it. The custom version they gave me was not a full, normal Storm distribution, so I used their change only to access the corrected storm.thrift from the pull request:

https://github.com/AirSage/Petrel/blob/master/petrel/setup.py#L48-L49

Once that change is actually in Storm (1.0.2 and beyond), we should change Petrel again to use the real one instead of from the pull request.

**Comment by CogumelosMaravilha** [comment]
It's working for me.
Thanks a lot.
Storm 1.0.1 + Petrel 1.0.1

**Comment by barrywhart** [comment]
Hurrah! Most difficult upgrade yet. :-)

**Comment by CogumelosMaravilha** [comment]
Yes, but now you are already prepared for 1.0.2!

**Comment by barrywhart** [comment]
The strange thing is, I don't actually use Storm for anything. Maybe in my next job (starting Monday).

**Comment by CogumelosMaravilha** [comment]
I hope so! A big data project. Good luck for the next job.
And thanks for maintaining Petrel without using it.
