### ISSUE TITLE
Storm warning: Using deprecated config nimbus.host

### ISSUE THREAD

**Issue by barrywhart** [AirSage/Petrel#78]
622 [main] WARN o.a.s.u.NimbusClient - Using deprecated config nimbus.host for backward compatibility. Please update your storm.yaml so it only has config nimbus.seeds.

**Comment by CogumelosMaravilha** [comment]
Solved.
Can close issue.

The old 0.10 conf file don't work on 1.0.1, an by mistake I change the conf file:
 my old local file;
 storm.messaging.transport: "backtype.storm.messaging.netty.Context"
 storm.messaging.netty.server_worker_threads: 1
 storm.messaging.netty.client_worker_threads: 1
 storm.messaging.netty.buffer_size: 5242880
 storm.messaging.netty.max_retries: 100
 storm.messaging.netty.max_wait_ms: 1000
 storm.messaging.netty.min_wait_ms: 100

 storm.zookeeper.servers:
     - "localhost"

 storm.zookeeper.port: 2181

 nimbus.host: "localhost"

 nimbus.thrift.port: 6627

 ui.port: 8772

 storm.local.dir: /usr/local/storm/data 

 supervisor.slots.ports:
   - 6700
   - 6701
   - 6702
   - 6703

**Comment by woisnow** [comment]
where is new conf file on new version "1.0.1"?

**Comment by barrywhart** [comment]
Petrel doesn't contain a .conf file, but you can supply one with your topology for Storm to use.

Unless you mean this file, maybe? https://github.com/AirSage/Petrel/blob/master/samples/wordcount/topology.yaml

**Comment by woisnow** [comment]
I want to know  how to config my storm. yaml(veraion: 1.0.1). When i config my  storm like this: i  install  zookeeper and  nimbus  in one system, i  config  zookeeper  host "192.168.1.108" and  nimbus.sweds "192.168.1.108", my  storm ui say warning:  like issue #78  and  in ui web the  nimbus  and supervisor  host showing "localhost",  i  search the solution on the  web ,many result is changing the hostname, but  i don't want to change my hostname. how  i can do?  and noting in my supervisor.log when i start supervisor, why?

**Comment by barrywhart** [comment]
Your question seems to be about Storm, not Petrel. I'm afraid I can't help you with this.
