### ISSUE TITLE
can not work well with storm 1.0.2

### ISSUE THREAD

**Issue by xiaodin1** [AirSage/Petrel#81]
my storm version is 1.0.2, when i use the commad : petrel submit --config topology.yaml wordcount ,the spout and bolt can not work well.i wonna ask if the current version of petrel can not support storm 1.0.2?
please help me ~

**Comment by xiaodin1** [comment]
the error message as follows:

ava.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:


	at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:91) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.spout.ShellSpout.open(ShellSpout.java:94) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.daemon.executor$fn__7990$fn__8005.invoke(executor.clj:604) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) [storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
134237 [Thread-17-split-executor[3 3]] ERROR o.a.s.util - Async loop died!
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:


	at org.apache.storm.utils.ShellProcess.launch(ShellProcess.java:91) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.task.ShellBolt.prepare(ShellBolt.java:131) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.daemon.executor$fn__8058$fn__8071.invoke(executor.clj:795) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:482) [storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
20:14:58.300 [Thread-23-spout-executor[4 4]] ERROR org.apache.storm.daemon.executor -

**Comment by barrywhart** [comment]
Some suggestions:
* Verify that you are running Petrel 1.0.2.0.3 (The first 3 digits of the Petrel version must match the Storm version.)
* Try running in local mode, with Petrel logging to the current directory: `petrel submit --config topology.yaml --logdir $(pwd)`. This will write Petrel logs to the current directory. After it fails, you can examine those logs to figure out what happened.

**Comment by xiaodin1** [comment]
# **thanks for your help, i can run the program in local model , it take 5~6mins to start up which makes me think the program broken down .the success info like these: **But****
```
535562 [Thread-27] INFO  o.a.s.d.executor - TRANSFERING tuple [dest: 2 tuple: source: split:3, stream: default, id: {}, ["away"]]
535562 [Thread-27] INFO  o.a.s.d.executor - BOLT ack TASK: 3 TIME:  TUPLE: source: spout:4, stream: default, id: {}, ["an apple a day keeps the doctor away"]
535562 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["an"]
535562 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["an"] TASK: 2 DELTA: 
535563 [Thread-26] INFO  o.a.s.d.task - Emitting: count default ["an",154]
535563 [Thread-26] INFO  o.a.s.d.executor - BOLT ack TASK: 2 TIME:  TUPLE: source: split:3, stream: default, id: {}, ["an"]
535563 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["apple"]
535563 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["apple"] TASK: 2 DELTA: 
535563 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["a"]
535563 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["a"] TASK: 2 DELTA: 
535563 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["day"]
535564 [Thread-26] INFO  o.a.s.d.task - Emitting: count default ["apple",154]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["day"] TASK: 2 DELTA: 1
535564 [Thread-26] INFO  o.a.s.d.executor - BOLT ack TASK: 2 TIME:  TUPLE: source: split:3, stream: default, id: {}, ["apple"]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["keeps"]
535564 [Thread-26] INFO  o.a.s.d.task - Emitting: count default ["a",154]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["keeps"] TASK: 2 DELTA: 
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["the"]
535564 [Thread-26] INFO  o.a.s.d.executor - BOLT ack TASK: 2 TIME:  TUPLE: source: split:3, stream: default, id: {}, ["a"]
535564 [Thread-26] INFO  o.a.s.d.task - Emitting: count default ["day",154]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["the"] TASK: 2 DELTA: 
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["doctor"]
535564 [Thread-26] INFO  o.a.s.d.executor - BOLT ack TASK: 2 TIME:  TUPLE: source: split:3, stream: default, id: {}, ["day"]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["doctor"] TASK: 2 DELTA: 
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Processing received message FOR 2 TUPLE: source: split:3, stream: default, id: {}, ["away"]
535564 [Thread-15-count-executor[2 2]] INFO  o.a.s.d.executor - Execute done TUPLE source: split:3, stream: default, id: {}, ["away"] TASK: 2 DELTA: 
535564 [Thread-26] INFO  o.a.s.d.task - Emitting: count default ["keeps",154]
```

**# then i submit the program into the strom ,the spout and bolt all throw the exception:**

`java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: at org.apache.storm.utils.ShellProcess.launch( 	Wed, 14 Dec 2016 10:13:07`

**Comment by barrywhart** [comment]
Some other suggestions for finding the problem:
* Petrel writes logs, as noted above. If it's slow, see what's happening. Maybe you have lots of dependencies. Maybe your network is slow.
* When Petrel and Storm runs in cluster mode, Petrel still creates logs. Look at those logs and see what is failing. There are many possibilities.
* Try running a pure Java topology on your cluster. Does that work okay?

I'm afraid I can't walk you through every step of solving this. You will need some know-how with your system, Storm, and Python.

The book "Building Python Real-Time Applications with Storm" has more detailed information on Petrel log locations and may be helpful to you.

**Comment by xiaodin1** [comment]
i am reading the book ~ it's a really good book, i have tried to submit a pure java topology into the storm cluster, it works well. 
python 2.7
storm 1.0.2
petrel 1.0.2
centos7
by the way, where is the location of the petrel's logs?

**Comment by barrywhart** [comment]
On a cluster, I believe they are in the Storm Supervisor directory. The location of that directory should be shown in the regular Storm (Java) logs.

**Comment by xiaodin1** [comment]
i just installed in the nimbus and not install petrel in the supervisor, i think that maybe occur that problem?and i find  : 
```
[root@xiaoding01 wordcount]# tail -f petrel25929_virtualenv.log 
New python executable in /tmp/petrel-20topology-1-1481685334/venv/bin/python2.7
Also creating executable in /tmp/petrel-20topology-1-1481685334/venv/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2.7
Installing thrift==0.9.3
Requirement already satisfied: thrift==0.9.3 in /usr/lib/python2.7/site-packages/thrift-0.9.3-py2.7.egg
Installing PyYAML==3.10
Requirement already satisfied: PyYAML==3.10 in /usr/lib64/python2.7/site-packages
Installing Petrel from local file petrel-1.0.2.0.3-py2.7.egg
Processing petrel-1.0.2.0.3-py2.7.egg
creating /tmp/petrel-20topology-1-1481685334/venv/lib/python2.7/site-packages/petrel-1.0.2.0.3-py2.7.egg
Extracting petrel-1.0.2.0.3-py2.7.egg to /tmp/petrel-20topology-1-1481685334/venv/lib/python2.7/site-packages
Adding petrel 1.0.2.0.3 to easy-install.pth file
Installing petrel script to /tmp/petrel-20topology-1-1481685334/venv/bin

Installed /tmp/petrel-20topology-1-1481685334/venv/lib/python2.7/site-packages/petrel-1.0.2.0.3-py2.7.egg
Processing dependencies for petrel==1.0.2.0.3
Finished processing dependencies for petrel==1.0.2.0.3
```
upper log is produced in local model, i find it will take much time to  Installing setuptools, pip, wheel... and  my virture machine can not connected to the internet，it's a Local Area Network~is that made the start up time longer?

**Comment by barrywhart** [comment]
You might try installing the same Python libraries manually. If you're not connected to the internet, I don't know how those packages could install at all.

About Petrel and the cluster -- generally you won't install Petrel on the Storm worker machines, you just need Python 2.7 and virtualenv on each machine in the cluster. Petrel automatically creates a virtualenv and installs itself (plus other Python library dependencies) for each topology. Because the topology startup is doing all these things, there's a lot that can go wrong.

The supervisor directory should be printed at startup time. I think it's called "storm.local.dir". This is a base directory; the actual Storm directory is a level or two below. You should find log files much like the ones created by Petrel for a local topology.

**Comment by barrywhart** [comment]
This link may be helpful regarding storm.local.dir:
https://groups.google.com/forum/#!topic/storm-user/iwyTRjxbtM0

**Comment by xiaodin1** [comment]
i would tell you a good news ,i can run the sample wordcount in my storm cluster,i installed all the libraries manually, then submit the jar into the storm again, it works well. thanks .
through this progress, may i give you some advices:
1、the log can be more details~e.g.show the network situation, the installing steps
2、provide additional scripts to install the libraries and keep petrel module independent, i think that would be more robust
at last , i have a question, that petrel supply some interfaces to intergrate kafka
finally,i very appreciate your kindness to solve my problems ,thx~

**Comment by barrywhart** [comment]
The log should show the Python installation steps. See the following part of the code. This is a bash script that sets up the Python environment, then starts Petrel: https://github.com/AirSage/Petrel/blob/master/petrel/petrel/package.py#L271-L314

What kind of network information would you like to see?

>provide additional scripts to install the libraries and keep petrel module independent, i think that would make the project more robust

Please explain what you mean?

>At last , i have a question, that petrel supply some interfaces to intergrate kafka

Since I don't use Storm at work, I am mostly maintaining Petrel these days rather than adding new features. But I'm open to PRs for useful enhancements. I assume you're familiar with the kafka-python library? It should be fairly easy to use that to write a basic Kafka spout.

**Comment by xiaodin1** [comment]
i have read the Chapter 4. Example Topology – Twitter in the book, i have alreadly got the way to write a spout to get output stream from kafka, when i have a good knowledge of petrel, i think i would like to submit my code to your resposity, thx~

**Comment by barrywhart** [comment]
It sounds like your problem is solved. Closing this issue.
