### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by dmitry-saritasa** [AirSage/Petrel#87]
hi Barry,

where should I put requirements.txt so that petrel installs all the dependencies on actual apache storm cluster? In the same root directory where create.py is?

**Comment by barrywhart** [comment]
You should do the following:
* Create a requirements.txt file listing your requirements.
* Create a manifest.txt file.
* Create a setup.sh file containing the command `pip install -r requirements.txt`

Place these files in the directory with create.py. These files will be included in the topology.jar, and Petrel will run setup.sh when the topology is initializing. Here's the code that does that: 
https://github.com/AirSage/Petrel/blob/master/petrel/petrel/package.py#L314


If you have any issues, you will want to check the Petrel log file.

**Comment by barrywhart** [comment]
Closing since I answered the question and haven't heard back. Please reopen or create a new issue if necessary.
