### ISSUE TITLE
Caching inside bolt implementation

### ISSUE THREAD

**Issue by dmitry-saritasa** [AirSage/Petrel#89]
hi Barry,

**bolt.py**
```python
def run():
    """Default function needed to run bolt as task
    inside Apache Storm Topology
    """
    TheBolt().run()
```

If my bolt makes additional DB calls when new tuple is received inside **process** method (and I want to cache some information in local cache within bolt process ahead of time = i.e. cache pre-warming to avoid excessive DB usage) = is it a good idea to put several DB calls in mandatory **run()** function before **TheBolt().run()** line?

I'll be using LRU 
https://boltons.readthedocs.io/en/latest/cacheutils.html

So for example inside incoming tuple I'll have a element '42004e0a-2070-11e7-82a6-fcaa14297fe1' which represents unique UID of the user, but I need to convert it into internal INT ID, like 42004e0a-2070-11e7-82a6-fcaa14297fe1=1001, and that's why additional DB call is needed. I want to avoid excessive DB calls by caching this data inside bolt process before it runs ( i may have thousands of records to be pre-cached).

### My concerns:
- is run() func being called when apache worker starts, i.e. it will be called once only or every time a tuple comes in?
- if execution of pre-warmup call will be longer than 60 seconds - will Storm kill the bolt and will try to recreate process (i.e. endless loop because pre-warmup has not finished in time)?

Thanks,
Dmitry

**Comment by barrywhart** [comment]
`run()` will only be called when the worker starts.

I think the [`supervisor.worker.start.timeout.secs`](https://github.com/apache/storm/blob/master/conf/defaults.yaml#L150) controls how long Storm will wait for a worker to start up. Looks like the default is 120, but you could change this for your topology.

You could also consider doing that startup work in background threads or processes, although that adds complexity. Petrel and Storm won't know about those, so it'll be totally up to your code to manage them correctly (e.g. lifetime, concurrent data access).

**Comment by dmitry-saritasa** [comment]
thanks Barry
