### ISSUE TITLE
Debugging Python 3.5

### ISSUE THREAD

**Issue by dmitry-saritasa** [AirSage/Petrel#96]
@barrywhart 
how to debug the topology? 

```
petrel submit --venv self --config topology.yaml --logdir `pwd`
```

the topology is running but none of my pdb or ipdb calls are enforced. In some cases Storm just kills the worker regardless where I place

```
import ipdb
ipdb.set_trace()
```

winpdb doesn't work on python3.

```
(storm) ➜  src git:(master) ✗ winpdb
Traceback (most recent call last):
  File "/home/dmitry/.pyenv/versions/storm/bin/winpdb", line 84, in <module>
    import winpdb
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/winpdb.py", line 297, in <module>
    import rpdb2
  File "/home/dmitry/.pyenv/versions/3.5.2/envs/storm/lib/python3.5/site-packages/rpdb2.py", line 266, in <module>
    import SimpleXMLRPCServer 
ImportError: No module named 'SimpleXMLRPCServer'

```

**Comment by dmitry-saritasa** [comment]
I remember a long time ago I *think* (not sure) I was able to get into pdb shell, but it doesn't work right now. 

my *topology.yaml*:

```
nimbus.host: "nimbus"
# supervisor.worker.timeout.secs: 60
# topology.ackers: 1
# topology.workers: 1
# worker.childopts: "-Xmx4096m"
# topology.worker.childopts: "-Xmx4096m"

# In Storm 0.7.x, this is necessary in order to give workers time to
# initialize. In Storm 0.8.0 and later, it may not be necessary because Storm
# has added a separate, longer timeout for the initial launch of a worker.
supervisor.worker.timeout.secs: 60

topology.workers: 1

```

**Comment by barrywhart** [comment]
`pdb` is not usable because it requires access to stdin, but Storm uses that for communicating with the worker.

Some ways to debug:
* Write automated tests, debug in those.
* Use log statements.
* There is a library called [rpdb](https://coderwall.com/p/ttbtgq/python-remote-debugging-with-pdb) that lets you use pdb over a telnet connection.
